/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class core_CABPProxy */

#ifndef _Included_core_CABPProxy
#define _Included_core_CABPProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     core_CABPProxy
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_core_CABPProxy_clear
  (JNIEnv *, jobject);

/*
 * Class:     core_CABPProxy
 * Method:    position
 * Signature: ([I[I[I)I
 */
JNIEXPORT jint JNICALL Java_core_CABPProxy_position
  (JNIEnv *, jobject, jintArray, jintArray, jintArray);

/*
 * Class:     core_CABPProxy
 * Method:    addCommNode
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_core_CABPProxy_addCommNode
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     core_CABPProxy
 * Method:    addNonCommNode
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_core_CABPProxy_addNonCommNode
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     core_CABPProxy
 * Method:    getAreaPoints
 * Signature: ([I[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_core_CABPProxy_getAreaPoints
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     core_CABPProxy
 * Method:    getAreas
 * Signature: ([I[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_core_CABPProxy_getAreas
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
